### PR TITLE
Switch to using contextvars, in order to support Trio

### LINKED ISSUE #290: Generic coroutine support
Currently Eliot DTRT for asyncio coroutines only. It would be good to support all event loops (Twisted, Tornado, trio, curio, etc..)

One option: https://docs.python.org/3/library/sys.html#sys.set_coroutine_wrapper

In Python 3.7 might have context support, which would help too.

### LINKED ISSUE #396: Add example of using Trio (and maybe asyncio while I'm at it?)
Perhaps with https://medium.com/@pgjones/quart-trio-9415d7c1928a

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #290
Fixes #396

### CODE REVIEW

**Comment by itamarst** [comment]
This is broken. I need to switch to using just ContextVar.set/get, without managing our own stack; the latter is no longer necessary. And tests to demonstrate the problems I saw with Trio example.

**Comment by itamarst** [comment]
Should in theory work now, modulo minor fixes.

**Comment by itamarst** [comment]
@jtrakk would appreciate some testing, if you have the time.

**Comment by jtrakk** [comment]
I'm not sure what's supposed to happen if I continue an action in a subprocess (`trio.Process`) and an exception is raised inside that subprocess. I'm cancelling the parent with control-c, and seeing some exceptions. 

```
[...]
  File "/usr/lib/python3.7/contextlib.py", line 511, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.7/contextlib.py", line 496, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.7/contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "/home/user/Documents/project/venv/lib/python3.7/site-packages/eliot/_action.py", line 414, in __exit__
    _ACTION_CONTEXT.reset(self._parent_token)
ValueError: <Token var=<ContextVar name='eliot.action' at 0x7f51b550c048> at 0x7f51b3f631f8> was created in a different Context
```

**Comment by itamarst** [comment]
Could you share a minimal reproducer? Thanks!

**Comment by jtrakk** [comment]
The issue was due to my broken dual-purpose logging decorator implementation. I'll keep poking around and will update if I experience problems.

**Pull request merged**
